### ISSUE TITLE
Issue with update lag between Chrome and chromedriver-py

### ISSUE THREAD

**Issue by lundstrj** [breuerfelix/chromedriver-py#17]
Hello, sorry to bother you again.

My Google Chrome just now updated to Version 98.0.4758.102 (Official Build) (arm64) and there is a corresponding chromedriver in https://chromedriver.storage.googleapis.com/ but chromedriver-py has not yet been updated to include the new chromedriver.

I did see the readme section about github actions to trigger a new build for pushing a new version to pypi. I am guessing I'm not a developer and therefor cannot trigger the workflow.

Perhaps we have a way of running the workflow more often or ideally make it event driven, tied to whenever a new chrome release is made? (I'd also settle for being made a dev so I can trigger the workflow when necessary but I can understand how you'd prefer to keep the developer list short)

**Comment by breuerfelix** [comment]
okay we are on version 99 already ... i didnt thought that chrome is updating its library more than one time a day but it seems like they are doing this :D
i will update so it runs every hour :) this should pick up all releases in time i guess :)

**Comment by breuerfelix** [comment]
okay the issue was somewhere else... due to semver... i will rewrite the updater so it updates any version that is not yet uploaded. right now it just always tries to upload the newest one :) your version should be online right now!

feel free to always create an issue if a version is missing, shouldn't happen again after i push my fix :)

**Comment by lundstrj** [comment]
Thank you for such a swift fix, much appreciated.
